[package]
name = "sek"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[[bin]]
name = "seksh"
path = "src/main.rs"

[dependencies]
# utils
anyhow = "1"
smallvec = "1"

# options
argh = "0.1"
directories = "5"

# ui
crossterm = "0.28"
unicode-width = "0.2"
annotate-snippets = "0.11"

# lang
logos = "0.15"
